# Generated by Django 5.1 on 2024-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('home', 'Home & Garden'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games')], default='home', max_length=15),
        ),
    ]
