# Generated by Django 5.1 on 2024-08-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_name_listing_title_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('none', 'No Category'), ('home', 'Home & Garden'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games')], default='none', max_length=15),
        ),
    ]
