# Generated by Django 5.1 on 2024-08-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='value',
        ),
    ]
